packages:
  - .

allowBuilds:
  '@vercel/speed-insights': true
  bufferutil: false
  esbuild: true
  sharp: true
  unrs-resolver: true

peerDependencyRules:
  allowedVersions:
    tailwindcss: 4.3.0

overrides:
  '@types/react': 19.2.16
  '@types/react-dom': 19.2.3
