/**
 * The site's adapted Material 3 type roles. The brand guide and downloadable
 * kit consume this list; the unit test keeps app/globals.css in sync.
 */
export const typeScale = [
  {
    name: 'display-large',
    size: 57,
    lineHeight: 64,
    weight: 600,
    letterSpacing: '-0.04em',
    use: 'A short, singular statement on a wide landing page.',
    sample: 'Making things useful.',
  },
  {
    name: 'display-medium',
    size: 45,
    lineHeight: 52,
    weight: 600,
    letterSpacing: '-0.04em',
    use: 'A prominent introduction when the largest display is too much.',
    sample: 'Ideas in motion.',
  },
  {
    name: 'display-small',
    size: 36,
    lineHeight: 44,
    weight: 600,
    letterSpacing: '-0.04em',
    use: 'A compact hero or the main title of a visual page.',
    sample: 'Work worth sharing.',
  },
  {
    name: 'headline-large',
    size: 32,
    lineHeight: 40,
    weight: 700,
    letterSpacing: '-0.025em',
    use: 'The title of a substantial story or project page.',
    sample: 'A city that moves together',
  },
  {
    name: 'headline-medium',
    size: 28,
    lineHeight: 36,
    weight: 600,
    letterSpacing: '-0.025em',
    use: 'A page title or a major section with room to breathe.',
    sample: 'Finding a better route',
  },
  {
    name: 'headline-small',
    size: 24,
    lineHeight: 32,
    weight: 600,
    letterSpacing: '-0.025em',
    use: 'A section heading inside long-form content.',
    sample: 'What changed along the way',
  },
  {
    name: 'title-large',
    size: 22,
    lineHeight: 28,
    weight: 600,
    letterSpacing: '0em',
    use: 'A card, feature, or local content group title.',
    sample: 'A better way home',
  },
  {
    name: 'title-medium',
    size: 16,
    lineHeight: 24,
    weight: 500,
    letterSpacing: '0.015em',
    use: 'A list item or smaller content group title.',
    sample: 'The route in practice',
  },
  {
    name: 'title-small',
    size: 14,
    lineHeight: 20,
    weight: 500,
    letterSpacing: '0.01em',
    use: 'A compact row or supporting title.',
    sample: 'Notes from the road',
  },
  {
    name: 'body-large',
    size: 18,
    lineHeight: 28,
    weight: 400,
    letterSpacing: '0em',
    use: 'An introduction or optional subtitle below a title.',
    sample: 'Good work starts with listening to the people who use it.',
  },
  {
    name: 'body-medium',
    size: 16,
    lineHeight: 24,
    weight: 400,
    letterSpacing: '0em',
    use: 'The default for paragraphs and sustained reading.',
    sample: 'Every trip tells us something about the city around us.',
  },
  {
    name: 'body-small',
    size: 14,
    lineHeight: 16,
    weight: 400,
    letterSpacing: '0.04em',
    use: 'A short supporting note; use body medium for longer text.',
    sample: 'A note from the field.',
  },
  {
    name: 'label-large',
    size: 14,
    lineHeight: 20,
    weight: 600,
    letterSpacing: '0.01em',
    use: 'Buttons, prominent links, and navigation.',
    sample: 'Explore the work',
  },
  {
    name: 'label-medium',
    size: 12,
    lineHeight: 16,
    weight: 600,
    letterSpacing: '0.05em',
    use: 'Categories and compact interface labels.',
    sample: 'FIELD NOTES',
  },
  {
    name: 'label-small',
    size: 11,
    lineHeight: 16,
    weight: 600,
    letterSpacing: '0.025em',
    use: 'Tiny metadata with enough contrast and space.',
    sample: 'SEPTEMBER 2026',
  },
];

export const typeFamilies = [
  {
    name: 'Display',
    description:
      'A rare, expressive opening. Keep it brief and step down on narrow screens.',
  },
  {
    name: 'Headline',
    description: 'Names pages and major sections in a reading flow.',
  },
  {
    name: 'Title',
    description: 'Names local pieces of content, such as cards and list rows.',
  },
  {
    name: 'Body',
    description:
      'Carries the reading. Large introduces; medium sustains; small stays brief.',
  },
  {
    name: 'Label',
    description: 'Names an action or a compact piece of interface information.',
  },
];
