name: Build and Deploy Website

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    # TODO: Test website
    - name: Build website
      run: |
        npm ci
        npm run build
    - name: Deploy
      uses: w9jds/firebase-action@v1.0
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
